services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    ipc: host
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./target:/app/target
    environment:
      - MAVEN_OPTS=-Xmx1024m
